version: 0.0
os: linux
files:
  - source: /
    destination: /opt/reactapp

permissions:
- object: /
  pattern: "**"
  owner: root
  group: root

hooks:
  BeforeInstall:
    - location: script/beforeInstall.sh
      timeout: 100
      runas: root
    
  ApplicationStart:
     - location: script/start.sh
       timeout: 100
       runas: root
